dist: bionic
env:
    global:
    -   secure: qlOHM0AvUSG/xH+3odFA1uubFbbNo0Il0GwC1QKX2Ti1IS0objNZIKhYgqoLdiSgq0fNKkWFA8f6ffghKohaK/VjqxzbbXaHxhfYqeY2ipW/FDvo6R3bSec7daD1uHdNwTCjZK1Y+Bn/9i/vV1Hd63TO8RlRfda03FFgR8RAmbticVq9XkHX7eUl2H2FNgcO9o1Xba/VhetNtkCZT+dlth9GCm00ncoQv04DbdN7isovosoSjEKkU8P5y7H7xXuQFS6qt2QYFstqlOmJ2GMqYwFBWADnOV7IIVIztsi8q57NDjPkbrX8SBGBXi6jXzv5Xoc/F3crApO1lnrrpU1h7nzY/K2DKMKbDUvqNipohd9XyKBYfEvEuT7R6oBuf8T3R9q5lLw2xd9Z70yEVGhNeZifmIpmvULLRhUWNKeIwZInlouTqtLElYQrdqImlEtxR06YYJfJJSb3qmTYDkB4enS4Nym3NrR+1gUjFzIML97rQrcc5suflv5SdB6ayYBQVZvnvGUULsvQKVGt+xYM7M2gO1ZYy9kqA0b/Rnu3kb7xoCu3WRoBgUYPW1i2R3UM8QFia3wADlTUJAXpLFVcPGExk+5Q+/xiM8f7Qpj9jdSIyQuOc/fyc23g9N+F1wpiwjiW4b68bu284+Rib1BGLmYAOwyYN/vqWstWZPofpjc=
    -   GIT_NAME: Dead-Hosts
    -   GIT_EMAIL: dead-hosts@outlook.com
    -   GIT_BRANCH: master
    -   PYTHON_VERSION: 3.7.5
install:
- export PATH="${HOME}/miniconda/bin:${PATH}"
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p ${HOME}/miniconda
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda create -q -n launcher-environment python="${PYTHON_VERSION}"
- conda activate launcher-environment
- python -VV
- pip --version
- pip install --upgrade dead-hosts-launcher
- rm miniconda.sh
language: generic
notifications:
    email:
        on_failure: always
        on_success: change
        recipients:
        - dead-hosts@outlook.com
os:
- linux
script:
- dead_hosts_launcher --version
- dead_hosts_launcher
